$(function(){
    $('.blog-card').hover(
        function(){
            $('.title').addClass('hover');
        },
        function(){
            $('.title').removeClass('hover');
        }
    );
});